'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import {
  FileSpreadsheet, FileText, Calendar, Filter,
  TrendingUp, DollarSign, Users, PieChart,
  Download, RefreshCw, ShieldCheck, Zap,
  BarChart3, Search, Activity, Target, Layers,
  ChevronRight, ArrowUpRight, ArrowDownRight, UserCheck
} from 'lucide-react';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, BarChart, Bar, Cell,
  PieChart as RePieChart, Pie, Legend, LineChart, Line
} from 'recharts';
import { toast } from 'sonner';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportsPage() {
  const { data: session } = useSession();
  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [dateRange, setDateRange] = useState({
    start: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString().split('T')[0],
    end: new Date().toISOString().split('T')[0]
  });
  const [activeCategory, setActiveCategory] = useState('financial');
  const [searchTerm, setSearchTerm] = useState('');

  const isAdmin = ['ADMIN', 'MANAGER'].includes((session?.user as any)?.role);

  const fetchReport = async () => {
    setLoading(true);
    try {
      const query = new URLSearchParams({
        startDate: dateRange.start,
        endDate: dateRange.end,
        category: activeCategory
      }).toString();
      const response = await fetch(`/api/reports?${query}`);
      const data = await response.json();
      setReportData(data);
    } catch (error) {
      toast.error('Forensic data retrieval failed');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (session) fetchReport();
  }, [activeCategory, session]);

  // ─── Excel Export ───────────────────────────────────────────────────────────
  const exportAdvancedExcel = () => {
    if (!reportData?.payments) return;
    const wb = XLSX.utils.book_new();
    const now = new Date().toLocaleString();
    const role = (session?.user as any)?.role || 'USER';

    // ── Sheet 1: Summary ────────────────────────────────────────────────────
    const summaryRows = [
      ['YORDI EQUIB SYSTEM — FINANCIAL REPORT'],
      ['Generated By', session?.user?.name || 'Unknown', '', 'Role', role],
      ['Reporting Period', `${dateRange.start}  →  ${dateRange.end}`],
      ['Generated At', now],
      [],
      ['KPI METRICS'],
      ['Total Collection Volume (ETB)', reportData.summary?.totalVolume ?? 0],
      ['Total Transactions', reportData.summary?.txCount ?? 0],
      ['Average Transaction (ETB)', Math.round(reportData.summary?.avgTx ?? 0)],
      ...(isAdmin && reportData.intelligence?.staffPerformance
        ? [[], ['TOP COLLECTOR', reportData.intelligence.staffPerformance[0]?.full_name ?? '—']]
        : []),
    ];
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
    wsSummary['!cols'] = [{ wch: 32 }, { wch: 24 }, { wch: 10 }, { wch: 14 }, { wch: 20 }];
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

    // ── Sheet 2: Transaction Ledger ─────────────────────────────────────────
    const txRows = reportData.payments.map((p: any, idx: number) => ({
      '#': idx + 1,
      'Payment ID': p.id ?? '',
      'Payment Date': p.date ? new Date(p.date).toLocaleDateString() : '',
      'Eth. Year': p.ethiopian_year ?? '',
      'Customer ID': p.customer_id ?? '',
      'Customer Name': p.customer_name ?? '',
      'EKUB Type': p.ekub_type ?? '',
      'Round': p.round ?? '',
      'Period': p.period ?? '',
      'Status': 'PAID',
      'Amount (ETB)': Number(p.amount ?? 0),
      'Recorded By': p.recorded_by ?? 'System',
    }));
    const wsTx = XLSX.utils.json_to_sheet(txRows);
    wsTx['!cols'] = [
      { wch: 5 }, { wch: 38 }, { wch: 14 }, { wch: 10 }, { wch: 16 },
      { wch: 28 }, { wch: 14 }, { wch: 10 }, { wch: 14 }, { wch: 8 },
      { wch: 14 }, { wch: 22 },
    ];
    XLSX.utils.book_append_sheet(wb, wsTx, 'Transaction Ledger');

    // ── Sheet 3: Staff Performance (Admin only) ─────────────────────────────
    if (isAdmin && reportData.intelligence?.staffPerformance?.length) {
      const wsStaff = XLSX.utils.json_to_sheet(
        reportData.intelligence.staffPerformance.map((s: any, i: number) => ({
          '#': i + 1,
          'Staff Name': s.full_name,
          'Total Volume (ETB)': Number(s.total_volume ?? 0),
          'Transactions': Number(s.tx_count ?? 0),
        }))
      );
      wsStaff['!cols'] = [{ wch: 5 }, { wch: 28 }, { wch: 20 }, { wch: 14 }];
      XLSX.utils.book_append_sheet(wb, wsStaff, 'Staff Performance');
    }

    XLSX.writeFile(wb, `Yordi_Report_${dateRange.start}.xlsx`);
    toast.success('Excel workbook exported successfully');
  };

  // ─── PDF Export (async — loads logo + draws charts) ─────────────────────────
  const exportEnterprisePDF = async () => {
    if (!reportData?.payments) {
      toast.error('No data to export. Please wait for data to load.');
      return;
    }

    const role = (session?.user as any)?.role || 'USER';
    const docId = Math.random().toString(36).substring(2, 11).toUpperCase();
    const now = new Date();
    const W = 297; const H = 210; const margin = 14;

    const loadFontAsBase64 = async (fontUrl: string) => {
      const fontBuffer = await fetch(fontUrl).then((response) => response.arrayBuffer());
      let binary = '';
      const bytes = new Uint8Array(fontBuffer);
      for (let i = 0; i < bytes.length; i += 1) {
        binary += String.fromCharCode(bytes[i]);
      }
      return btoa(binary);
    };

    // ── Load logo as base64 ──────────────────────────────────────────────────
    let logoDataUrl: string | null = null;
    try {
      const blob = await fetch('/logo.png').then(r => r.blob());
      logoDataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch { logoDataUrl = null; }

    // ── Helper: draw page header (used on every addPage) ─────────────────────
    const drawHeader = (doc: jsPDF, pageLabel: string) => {
      // Dark band
      doc.setFillColor(5, 30, 55);
      doc.rect(0, 0, W, 28, 'F');
      // Blue stripe
      doc.setFillColor(1, 108, 196);
      doc.rect(0, 28, W, 2, 'F');

      // White logo box
      if (logoDataUrl) {
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(margin, 3, 32, 22, 2, 2, 'F');
        doc.addImage(logoDataUrl, 'PNG', margin + 1, 4, 30, 20);
      }

      // Title (shifted right when logo present)
      const titleX = logoDataUrl ? margin + 36 : margin;
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(17);
      doc.setFont('helvetica', 'bold');
      doc.text('YORDI EQUIB SYSTEM', titleX, 13);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.text('Ethiopian Traditional EKUB Management Platform', titleX, 21);

      // Right meta
      doc.setFontSize(7.5);
      doc.setTextColor(180, 210, 255);
      const mx = W - margin;
      doc.text(`Doc ID: ${docId}`, mx, 8, { align: 'right' });
      doc.text(`Section: ${pageLabel}`, mx, 13, { align: 'right' });
      doc.text(`${session?.user?.name ?? 'Unknown'} · ${role}`, mx, 18, { align: 'right' });
      doc.text(now.toLocaleString(), mx, 24, { align: 'right' });
    };

    // ── Helper: draw page footer ──────────────────────────────────────────────
    const drawFooter = (doc: jsPDF, pageNum: number) => {
      doc.setFontSize(6.5);
      doc.setTextColor(150);
      doc.setFont('helvetica', 'normal');
      doc.setDrawColor(200);
      doc.line(margin, H - 9, W - margin, H - 9);
      doc.text(`YORDI EQUIB — CONFIDENTIAL  |  Doc ID: ${docId}  |  Page ${pageNum}`, margin, H - 5);
      doc.text(`Generated: ${now.toLocaleString()}`, W - margin, H - 5, { align: 'right' });
    };

    // ── Helper: draw a vertical bar chart ────────────────────────────────────
    const drawBarChart = (
      doc: jsPDF,
      x: number, y: number, w: number, h: number,
      title: string,
      items: { label: string; value: number }[],
      color: [number, number, number]
    ) => {
      if (!items.length) return;
      const maxVal = Math.max(...items.map(d => d.value), 1);
      const innerH = h - 16;
      const innerW = w - 10;
      const barW = Math.max(Math.min(innerW / items.length - 3, 16), 4);

      // Background
      doc.setFillColor(247, 250, 254);
      doc.setDrawColor(210, 225, 240);
      doc.roundedRect(x, y, w, h, 2, 2, 'FD');

      // Title
      doc.setFontSize(7); doc.setFont('helvetica', 'bold');
      doc.setTextColor(50, 70, 100);
      doc.text(title, x + 4, y + 6);

      // Baseline
      doc.setDrawColor(200, 210, 225);
      doc.line(x + 5, y + h - 9, x + w - 5, y + h - 9);

      // Bars + labels
      items.forEach((d, i) => {
        const bx = x + 6 + i * (innerW / items.length);
        const bh = Math.max((d.value / maxVal) * innerH, 1);
        const by = y + h - 9 - bh;
        doc.setFillColor(...color);
        doc.rect(bx, by, barW, bh, 'F');
        // Value on top
        doc.setFontSize(5); doc.setFont('helvetica', 'bold');
        doc.setTextColor(...color);
        if (bh > 5) doc.text(d.value.toLocaleString(), bx + barW / 2, by - 1, { align: 'center' });
        // X-label
        doc.setFontSize(4.5); doc.setFont('helvetica', 'normal');
        doc.setTextColor(120, 140, 160);
        doc.text(String(d.label).substring(0, 6), bx + barW / 2, y + h - 5, { align: 'center' });
      });
    };

    // ── Helper: draw a horizontal bar chart (staff) ───────────────────────────
    const drawHBarChart = (
      doc: jsPDF,
      x: number, y: number, w: number, h: number,
      title: string,
      items: { label: string; value: number }[]
    ) => {
      if (!items.length) return;
      const maxVal = Math.max(...items.map(d => d.value), 1);
      const rowH = Math.min((h - 12) / items.length, 10);
      const innerW = w - 60;

      doc.setFillColor(247, 250, 254);
      doc.setDrawColor(210, 225, 240);
      doc.roundedRect(x, y, w, h, 2, 2, 'FD');
      doc.setFontSize(7); doc.setFont('helvetica', 'bold');
      doc.setTextColor(50, 70, 100);
      doc.text(title, x + 4, y + 6);

      items.slice(0, Math.floor((h - 14) / rowH)).forEach((d, i) => {
        const by = y + 10 + i * rowH;
        const bw = (d.value / maxVal) * innerW;
        // Name
        doc.setFontSize(5.5); doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 80, 110);
        doc.text(d.label.substring(0, 18), x + 4, by + rowH - 2);
        // Bar
        doc.setFillColor(16, 185, 129);
        doc.rect(x + 52, by, bw, rowH - 2, 'F');
        // Value
        doc.setFontSize(5); doc.setFont('helvetica', 'bold');
        doc.setTextColor(16, 100, 70);
        doc.text(d.value.toLocaleString(), x + 54 + bw, by + rowH - 3);
      });
    };

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 1 — Dashboard + Transaction Table
    // ══════════════════════════════════════════════════════════════════════════
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    try {
      const nyalaFont = await loadFontAsBase64('/fonts/nyala.ttf');
      doc.addFileToVFS('Nyala.ttf', nyalaFont);
      doc.addFont('Nyala.ttf', 'Nyala', 'normal');
    } catch {
      // Fall back to built-in fonts if the bundled font cannot be loaded.
    }

    drawHeader(doc, 'FINANCIAL OVERVIEW');

    // Metadata strip
    doc.setTextColor(60, 80, 100);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Period: ${dateRange.start}  →  ${dateRange.end}`, margin, 37);
    doc.text(`Category: ${activeCategory.toUpperCase()}`, margin + 110, 37);
    doc.text(`Records: ${reportData.payments.length}`, margin + 220, 37);

    // KPI boxes — 3 boxes, evenly spread across full width
    const kpis = [
      { label: 'NET COLLECTION (ETB)', value: Number(reportData.summary?.totalVolume ?? 0).toLocaleString(), color: [1, 108, 196] as [number, number, number] },
      { label: 'TOTAL TRANSACTIONS', value: String(reportData.summary?.txCount ?? 0), color: [16, 185, 129] as [number, number, number] },
      { label: 'AVG. AMOUNT (ETB)', value: Math.round(reportData.summary?.avgTx ?? 0).toLocaleString(), color: [245, 158, 11] as [number, number, number] },
    ];
    const boxW = (W - margin * 2 - 8) / 3;
    const boxH = 18; const boxY = 42;
    kpis.forEach((kpi, i) => {
      const bx = margin + i * (boxW + 4);
      // Left accent bar
      doc.setFillColor(...kpi.color);
      doc.rect(bx, boxY, 3, boxH, 'F');
      // Box background
      doc.setFillColor(248, 251, 255);
      doc.setDrawColor(220, 232, 245);
      doc.rect(bx + 3, boxY, boxW - 3, boxH, 'FD');
      // Label
      doc.setFontSize(6.5); doc.setFont('helvetica', 'bold');
      doc.setTextColor(120, 140, 165);
      doc.text(kpi.label, bx + 7, boxY + 6);
      // Value
      doc.setFontSize(13); doc.setFont('helvetica', 'bold');
      doc.setTextColor(...kpi.color);
      doc.text(kpi.value, bx + 7, boxY + 15);
    });

    // Transaction table
    const tableY = 64;
    doc.setFontSize(8); doc.setFont('helvetica', 'bold');
    doc.setTextColor(5, 30, 55);
    doc.text('TRANSACTION AUDIT LEDGER', margin, tableY - 1);

    let pageCount = 1;
    autoTable(doc, {
      startY: tableY,
      margin: { left: margin, right: margin },
      head: [['#', 'DATE', 'ETH.YR', 'CUST. ID', 'CUSTOMER NAME', 'EKUB TYPE', 'ROUND', 'PERIOD', 'AMOUNT (ETB)', 'RECORDED BY']],
      body: reportData.payments.map((p: any, idx: number) => [
        idx + 1,
        p.date ? new Date(p.date).toLocaleDateString() : '—',
        p.ethiopian_year ?? '—',
        p.customer_id ?? '—',
        p.customer_name ?? '—',
        p.ekub_type ?? '—',
        p.round ?? '—',
        p.period ?? '—',
        Number(p.amount ?? 0).toLocaleString(),
        p.recorded_by ?? 'System',
      ]),
      headStyles: { fillColor: [5, 30, 55], textColor: [255, 255, 255], fontSize: 7, fontStyle: 'bold', halign: 'center' },
      styles: { font: 'Nyala', fontStyle: 'normal', fontSize: 6.5, cellPadding: 2, overflow: 'ellipsize' },
      alternateRowStyles: { fillColor: [245, 249, 255] },
      columnStyles: {
        0: { halign: 'center', cellWidth: 7 },
        1: { cellWidth: 21 },
        2: { halign: 'center', cellWidth: 13 },
        3: { cellWidth: 22 },
        4: { cellWidth: 42 },
        5: { cellWidth: 22 },
        6: { cellWidth: 16 },
        7: { cellWidth: 18 },
        8: { halign: 'right', cellWidth: 24 },
        9: { cellWidth: 30 },
      },
      didDrawPage: (data: any) => {
        pageCount = data.pageNumber;
        drawFooter(doc, data.pageNumber);
      },
    });

    // Signature block (if space)
    const sigY = Math.min((doc as any).lastAutoTable?.finalY ?? 160, H - 32) + 6;
    if (sigY < H - 22) {
      doc.setDrawColor(180); doc.setFontSize(7); doc.setTextColor(80);
      doc.setFont('helvetica', 'normal');
      doc.line(margin, sigY + 8, margin + 55, sigY + 8);
      doc.text('Authorized Signature', margin, sigY + 12);
      doc.line(W / 2, sigY + 8, W / 2 + 55, sigY + 8);
      doc.text('Date & Stamp', W / 2, sigY + 12);
    }

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 2 — Analytics & Charts
    // ══════════════════════════════════════════════════════════════════════════
    doc.addPage();
    pageCount++;
    drawHeader(doc, 'ANALYTICS & CHARTS');
    drawFooter(doc, pageCount);

    // Layout constants for chart page
    // Usable area: Y=33 to Y=196 (before footer at 201)
    const CY_START = 34;       // top of chart area
    const CY_MID = 116;      // middle separator
    const CY_END = 196;      // bottom of chart area
    const ROW_H = CY_MID - CY_START - 4;  // ~78mm per row
    const BOT_H = CY_END - CY_MID - 4;    // ~76mm per row
    const HALF_W = (W - margin * 2 - 6) / 2;

    // Horizontal divider between rows
    doc.setDrawColor(220, 228, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, CY_MID, W - margin, CY_MID);
    doc.setLineWidth(0.2);

    // Section label
    doc.setFontSize(7); doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 120, 150);
    doc.text('FINANCIAL & OPERATIONAL METRICS', margin, CY_START - 1);
    doc.text(isAdmin ? 'GROWTH & STAFF PERFORMANCE' : 'MY COLLECTION TREND', margin, CY_MID + 3);

    // ── Row 1: Financial Audit (left) + Operational Velocity (right) ──────────
    const financialItems = (reportData.financialTrend ?? []).map((d: any) => ({
      label: String(d.label).substring(5),
      value: Number(d.amount),
    }));
    drawBarChart(
      doc, margin, CY_START + 4, HALF_W, ROW_H,
      'FINANCIAL AUDIT  -  Daily Collection (ETB)',
      financialItems.length ? financialItems : [{ label: '-', value: 0 }],
      [1, 108, 196]
    );

    const opsItems = (reportData.opsTrend ?? []).map((d: any) => ({
      label: String(d.label).substring(5),
      value: Number(d.count),
    }));
    drawBarChart(
      doc, margin + HALF_W + 6, CY_START + 4, HALF_W, ROW_H,
      'OPERATIONAL VELOCITY  -  Daily Transactions',
      opsItems.length ? opsItems : [{ label: '-', value: 0 }],
      [99, 102, 241]
    );

    // ── Row 2: Role-based charts ──────────────────────────────────────────────
    if (isAdmin) {
      const growthItems = (reportData.growthTrend ?? []).map((d: any) => ({
        label: String(d.label).substring(5),
        value: Number(d.count),
      }));
      drawBarChart(
        doc, margin, CY_MID + 5, HALF_W, BOT_H,
        'MEMBER GROWTH  -  New Registrations Per Day',
        growthItems.length ? growthItems : [{ label: '-', value: 0 }],
        [16, 185, 129]
      );

      const staffItems = (reportData.intelligence?.staffPerformance ?? []).map((s: any) => ({
        label: s.full_name ?? 'Unknown',
        value: Number(s.total_volume ?? 0),
      }));
      drawHBarChart(
        doc, margin + HALF_W + 6, CY_MID + 5, HALF_W, BOT_H,
        'STAFF PERFORMANCE  -  Total Volume (ETB)',
        staffItems
      );
    } else {
      const amountItems = (reportData.financialTrend ?? []).map((d: any) => ({
        label: String(d.label).substring(5),
        value: Number(d.amount),
      }));
      drawBarChart(
        doc, margin, CY_MID + 5, W - margin * 2, BOT_H,
        'MY COLLECTION TREND  -  Cumulative Amount (ETB)',
        amountItems.length ? amountItems : [{ label: '-', value: 0 }],
        [245, 158, 11]
      );
    }

    doc.save(`YORDI_REPORT_${dateRange.start}_${docId}.pdf`);
    toast.success('Professional PDF report exported successfully');
  };

  const CATEGORIES = [
    { id: 'financial', label: 'Financial Audit', icon: <DollarSign size={18} />, adminOnly: false },
    { id: 'growth', label: 'Member Growth', icon: <TrendingUp size={18} />, adminOnly: true },
    { id: 'staff', label: 'Staff Performance', icon: <UserCheck size={18} />, adminOnly: true },
    { id: 'ops', label: 'Operational Velocity', icon: <Zap size={18} />, adminOnly: false },
  ];

  const staffPerformanceData = (reportData?.intelligence?.staffPerformance ?? []).map((item: any) => ({
    ...item,
    total_volume: Number(item.total_volume ?? 0),
  }));
  const staffPerformanceMax = staffPerformanceData.length
    ? Math.max(...staffPerformanceData.map((item: any) => item.total_volume), 0)
    : 0;
  const staffYAxisMax = Math.max(Math.ceil((staffPerformanceMax || 1) / 5000) * 5000, 5000);
  const formatEtbCompact = (value: number) => {
    const absoluteValue = Math.abs(Number(value) || 0);
    if (absoluteValue >= 1000) {
      const compactValue = absoluteValue / 1000;
      const formattedValue = Number.isInteger(compactValue)
        ? compactValue.toFixed(0)
        : compactValue.toFixed(1).replace(/\.0$/, '');
      return `ETB ${Number(value) < 0 ? '-' : ''}${formattedValue}K`;
    }

    return `ETB ${Number(value).toLocaleString()}`;
  };

  const filteredPayments = reportData?.payments?.filter((p: any) =>
    p.customer_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.customer_id.toLowerCase().includes(searchTerm.toLowerCase())
  ) || [];

  return (
    <div className="p-4 md:p-8 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports Center</h1>
          <p className="text-gray-500 text-sm mt-1">Financial auditing & performance metrics</p>
        </div>

        <div className="flex items-center gap-3 w-full lg:w-auto">
          <button
            onClick={exportEnterprisePDF}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-all"
          >
            <FileText size={16} className="text-rose-500" />
            Export PDF
          </button>
          <button
            onClick={exportAdvancedExcel}
            className="flex-1 lg:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-gray-800 text-white rounded-lg text-sm font-medium hover:bg-gray-900 transition-all"
          >
            <FileSpreadsheet size={16} className="text-emerald-400" />
            Export Excel
          </button>
        </div>
      </div>

      {/* Intelligence Selector & Filters */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 mb-8">
        <div className="space-y-2">
          <p className="text-xs font-medium text-gray-500 mb-2">Report Categories</p>
          {CATEGORIES.filter(c => !c.adminOnly || isAdmin).map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`w-full flex items-center justify-between p-3 rounded-lg border transition-all ${activeCategory === cat.id
                ? 'bg-white border-gray-300 shadow-sm text-gray-900'
                : 'bg-transparent border-transparent text-gray-500 hover:bg-gray-100'
                }`}
            >
              <div className="flex items-center gap-3">
                <div className={`p-2 rounded-md ${activeCategory === cat.id ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-500'}`}>
                  {cat.icon}
                </div>
                <span className="text-sm font-medium">{cat.label}</span>
              </div>
              <ChevronRight size={16} className={activeCategory === cat.id ? 'text-gray-400' : 'hidden'} />
            </button>
          ))}
        </div>

        <div className="lg:col-span-3">
          <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
            <div className="flex flex-col md:flex-row items-end gap-4">
              <div className="flex-1 space-y-1.5 w-full">
                <label className="text-xs font-medium text-gray-500">Reporting Period</label>
                <div className="flex items-center gap-3">
                  <div className="relative flex-1">
                    <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={14} />
                    <input
                      type="date"
                      value={dateRange.start}
                      onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
                      className="w-full pl-9 pr-3 py-2 bg-white border border-gray-200 rounded-lg outline-none focus:border-gray-400 text-sm"
                    />
                  </div>
                  <span className="text-gray-400">to</span>
                  <div className="relative flex-1">
                    <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={14} />
                    <input
                      type="date"
                      value={dateRange.end}
                      onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
                      className="w-full pl-9 pr-3 py-2 bg-white border border-gray-200 rounded-lg outline-none focus:border-gray-400 text-sm"
                    />
                  </div>
                </div>
              </div>
              <button
                onClick={fetchReport}
                className="px-5 py-2 bg-gray-800 text-white rounded-lg text-sm font-medium hover:bg-gray-900 transition-all flex items-center gap-2"
              >
                <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
                Refresh
              </button>
            </div>

            {/* Chart Section */}
            <div className="mt-6 h-80">
              {loading ? (
                <div className="h-full flex flex-col items-center justify-center">
                  <div className="w-8 h-8 border-2 border-gray-200 border-t-gray-800 rounded-full animate-spin"></div>
                  <p className="text-xs text-gray-400 mt-3">Loading data...</p>
                </div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  {activeCategory === 'staff' ? (
                    <BarChart data={staffPerformanceData} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                      <XAxis dataKey="full_name" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <YAxis
                        axisLine={false}
                        tickLine={false}
                        allowDecimals={false}
                        domain={[0, staffYAxisMax]}
                        tickCount={6}
                        tick={{ fill: '#94a3b8', fontSize: 11 }}
                        tickFormatter={(value) => formatEtbCompact(Number(value))}
                      />
                      <Tooltip
                        contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0' }}
                        formatter={(value: any) => [formatEtbCompact(Number(value)), 'Total Volume']}
                      />
                      <Bar dataKey="total_volume" fill="#091A2B" radius={[4, 4, 0, 0]} barSize={40} />
                    </BarChart>
                  ) : activeCategory === 'ops' ? (
                    <BarChart data={reportData?.opsTrend || []} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                      <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0' }} formatter={(v) => [`${v} Payments`, 'Throughput']} />
                      <Bar dataKey="count" fill="#4a7c9c" radius={[4, 4, 0, 0]} barSize={40} />
                    </BarChart>
                  ) : activeCategory === 'growth' ? (
                    <LineChart data={reportData?.growthTrend || []} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                      <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0' }} />
                      <Line type="monotone" dataKey="count" stroke="#091A2B" strokeWidth={2} dot={{ r: 4, fill: '#091A2B' }} activeDot={{ r: 6 }} />
                    </LineChart>
                  ) : (
                    <AreaChart data={reportData?.financialTrend || []} margin={{ top: 20, right: 30, left: 20, bottom: 20 }}>
                      <defs>
                        <linearGradient id="velocityGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#091A2B" stopOpacity={0.1} />
                          <stop offset="95%" stopColor="#091A2B" stopOpacity={0} />
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0" />
                      <XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} dy={10} />
                      <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 11 }} />
                      <Tooltip contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0' }} />
                      <Area type="monotone" dataKey="amount" stroke="#091A2B" strokeWidth={2} fill="url(#velocityGrad)" />
                    </AreaChart>
                  )}
                </ResponsiveContainer>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* KPI Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-8">
        <div className="bg-white p-5 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-500 text-xs font-medium uppercase">Net Volume</p>
              <p className="text-xl font-bold text-gray-900 mt-1">ETB {reportData?.summary?.totalVolume.toLocaleString() || '0'}</p>
            </div>
            <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
              <DollarSign size={20} className="text-gray-600" />
            </div>
          </div>
        </div>

        <div className="bg-white p-5 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-500 text-xs font-medium uppercase">Transactions</p>
              <p className="text-xl font-bold text-gray-900 mt-1">{reportData?.summary?.txCount || '0'}</p>
            </div>
            <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
              <Activity size={20} className="text-gray-600" />
            </div>
          </div>
        </div>

        <div className="bg-white p-5 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-500 text-xs font-medium uppercase">Average Amount</p>
              <p className="text-xl font-bold text-gray-900 mt-1">ETB {Math.round(reportData?.summary?.avgTx || 0).toLocaleString()}</p>
            </div>
            <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
              <TrendingUp size={20} className="text-gray-600" />
            </div>
          </div>
        </div>

        <div className="bg-white p-5 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-gray-500 text-xs font-medium uppercase">Growth Index</p>
              <p className="text-xl font-bold text-gray-900 mt-1">+{reportData?.growthTrend?.length || 0}%</p>
            </div>
            <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
              <Target size={20} className="text-gray-600" />
            </div>
          </div>
        </div>
      </div>

      {/* Transaction Table */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
        <div className="p-5 border-b border-gray-200 flex flex-col md:flex-row justify-between items-center gap-4">
          <div>
            <h3 className="text-base font-semibold text-gray-900">Transaction Ledger</h3>
            <p className="text-xs text-gray-500 mt-0.5">Audit trail of all transactions</p>
          </div>
          <div className="relative w-full md:w-80">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} />
            <input
              type="text"
              placeholder="Search by customer or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 bg-white border border-gray-200 rounded-lg text-sm outline-none focus:border-gray-400"
            />
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">#</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Eth. Year</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Customer</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Scheme</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Period</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Recorded By</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filteredPayments.map((p: any, idx: number) => (
                <tr key={p.id} className="hover:bg-gray-50 transition">
                  <td className="px-6 py-4 text-sm text-gray-400">{idx + 1}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{new Date(p.date).toLocaleDateString()}</td>
                  <td className="px-6 py-4 text-sm font-semibold text-purple-700">{p.ethiopian_year ?? '—'}</td>
                  <td className="px-6 py-4">
                    <span className="text-sm font-medium text-gray-900">{p.customer_name}</span>
                  </td>
                  <td className="px-6 py-4 text-xs font-mono text-gray-500">{p.customer_id}</td>
                  <td className="px-6 py-4">
                    <span className="inline-block px-2 py-1 bg-gray-100 text-gray-700 rounded text-xs">{p.ekub_type}</span>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{p.period ?? '—'}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{p.recorded_by ? p.recorded_by.split(' ')[0] : 'System'}</td>
                  <td className="px-6 py-4 text-right text-sm font-semibold text-gray-900">ETB {Number(p.amount).toLocaleString()}</td>
                </tr>
              ))}
              {filteredPayments.length === 0 && (
                <tr>
                  <td colSpan={9} className="px-6 py-12 text-center text-gray-400">
                    No transactions found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}